package com.xworkz.interfaces.implementation1;

import com.xworkz.interfaces.interfaces.*;

public class Main {
    public static void main(String[] args) {
        IAirConditioner airConditionerObj = new AirConditionerImpl();
        airConditionerObj.turnOn();
        airConditionerObj.turnOff();
        airConditionerObj.setTemperature();
        airConditionerObj.drillWall();
        System.out.println("");
        IAirPurifier airPurifierObj = new AirPurifierImpl();
        airPurifierObj.purifyAir();
        airPurifierObj.changeFilter();
        airPurifierObj.turnOn();
        airPurifierObj.fixFrame();
        System.out.println("");
        IBarcodeScanner barcodeScannerObj = new BarcodeScannerImpl();
        barcodeScannerObj.scan();
        barcodeScannerObj.beep();
        barcodeScannerObj.connect();
        barcodeScannerObj.insertScrew();
        System.out.println("");
        IBattery batteryObj = new BatteryImpl();
        batteryObj.charge();
        batteryObj.discharge();
        batteryObj.checkLevel();
        batteryObj.alignShelf();
        System.out.println("");
        IBlender blenderObj = new BlenderImpl();
        blenderObj.blend();
        blenderObj.pulse();
        blenderObj.clean();
        blenderObj.mountTV();
        System.out.println("");
        IBluetoothHeadset bluetoothHeadsetObj = new BluetoothHeadsetImpl();
        bluetoothHeadsetObj.connect();
        bluetoothHeadsetObj.playMusic();
        bluetoothHeadsetObj.answerCall();
        bluetoothHeadsetObj.hangPicture();
        System.out.println("");
        ICamera cameraObj = new CameraImpl();
        cameraObj.clickPhoto();
        cameraObj.recordVideo();
        cameraObj.zoom();
        cameraObj.installBracket();
        System.out.println("");
        ICar carObj = new CarImpl();
        carObj.startEngine();
        carObj.stopEngine();
        carObj.honk();
        carObj.boreHole();
        System.out.println("");
        ICarKey carKeyObj = new CarKeyImpl();
        carKeyObj.lock();
        carKeyObj.unlock();
        carKeyObj.panicAlarm();
        carKeyObj.secureBolt();
        System.out.println("");
        ICeilingFan ceilingFanObj = new CeilingFanImpl();
        ceilingFanObj.setSpeed();
        ceilingFanObj.reverseDirection();
        ceilingFanObj.stop();
        ceilingFanObj.tapAnchor();
        System.out.println("");
        IChair chairObj = new ChairImpl();
        chairObj.sit();
        chairObj.adjustHeight();
        chairObj.rotate();
        chairObj.fitPlug();
        System.out.println("");
        IClock clockObj = new ClockImpl();
        clockObj.showTime();
        clockObj.setAlarm();
        clockObj.stopAlarm();
        clockObj.attachPanel();
        System.out.println("");
        ICoffeeMachine coffeeMachineObj = new CoffeeMachineImpl();
        coffeeMachineObj.brewCoffee();
        coffeeMachineObj.steamMilk();
        coffeeMachineObj.clean();
        coffeeMachineObj.grindSurface();
        System.out.println("");
        IDoorBell doorBellObj = new DoorBellImpl();
        doorBellObj.ring();
        doorBellObj.recordVisitor();
        doorBellObj.notifyUser();
        doorBellObj.chipPaint();
        System.out.println("");
        IDoorSensor doorSensorObj = new DoorSensorImpl();
        doorSensorObj.detectOpen();
        doorSensorObj.detectClose();
        doorSensorObj.sendAlert();
        doorSensorObj.routeCable();
        System.out.println("");
        IDrone droneObj = new DroneImpl();
        droneObj.takeOff();
        droneObj.land();
        droneObj.fly();
        droneObj.setDrillSpeed();
        System.out.println("");
        IElectricKettle electricKettleObj = new ElectricKettleImpl();
        electricKettleObj.boilWater();
        electricKettleObj.autoOff();
        electricKettleObj.keepWarm();
        electricKettleObj.measureDepth();
        System.out.println("");
        IElectricStove electricStoveObj = new ElectricStoveImpl();
        electricStoveObj.turnOn();
        electricStoveObj.adjustHeat();
        electricStoveObj.turnOff();
        electricStoveObj.positionHole();
        System.out.println("");
        IeReader eReaderObj = new eReaderImpl();
        eReaderObj.openBook();
        eReaderObj.turnPage();
        eReaderObj.bookmarkPage();
        eReaderObj.cleanDust();
        System.out.println("");
        IFan fanObj = new FanImpl();
        fanObj.switchOn();
        fanObj.switchOff();
        fanObj.rotate();
        fanObj.holdDrillFirm();
        System.out.println("");
        IFireAlarm fireAlarmObj = new FireAlarmImpl();
        fireAlarmObj.detectSmoke();
        fireAlarmObj.soundAlarm();
        fireAlarmObj.reset();
        fireAlarmObj.replaceBit();
        System.out.println("");
        IFitnessTracker fitnessTrackerObj = new FitnessTrackerImpl();
        fitnessTrackerObj.countSteps();
        fitnessTrackerObj.trackSleep();
        fitnessTrackerObj.monitorHeartRate();
        fitnessTrackerObj.tightenNut();
        System.out.println("");
        IFlashlight flashlightObj = new FlashlightImpl();
        flashlightObj.turnOn();
        flashlightObj.adjustBeam();
        flashlightObj.blink();
        flashlightObj.sandEdge();
        System.out.println("");
        IGameConsole gameConsoleObj = new GameConsoleImpl();
        gameConsoleObj.startGame();
        gameConsoleObj.pauseGame();
        gameConsoleObj.saveGame();
        gameConsoleObj.checkLevel();
        System.out.println("");
        IGarageDoor garageDoorObj = new GarageDoorImpl();
        garageDoorObj.open();
        garageDoorObj.close();
        garageDoorObj.lock();
        garageDoorObj.preDrill();
        System.out.println("");
        IGPSDevice gPSDeviceObj = new GPSDeviceImpl();
        gPSDeviceObj.navigate();
        gPSDeviceObj.recalculateRoute();
        gPSDeviceObj.showMap();
        gPSDeviceObj.markSpot();
        System.out.println("");
        IHairDryer hairDryerObj = new HairDryerImpl();
        hairDryerObj.turnOn();
        hairDryerObj.adjustHeat();
        hairDryerObj.coolShot();
        hairDryerObj.clampItem();
        System.out.println("");
        IHeater heaterObj = new HeaterImpl();
        heaterObj.turnOn();
        heaterObj.turnOff();
        heaterObj.setTemperature();
        heaterObj.hammerNail();
        System.out.println("");
        IIntercom intercomObj = new IntercomImpl();
        intercomObj.call();
        intercomObj.receiveCall();
        intercomObj.endCall();
        intercomObj.removeScrew();
        System.out.println("");
        IInverter inverterObj = new InverterImpl();
        inverterObj.supplyPower();
        inverterObj.chargeBattery();
        inverterObj.switchMode();
        inverterObj.findStud();
        System.out.println("");
        IJuicer juicerObj = new JuicerImpl();
        juicerObj.juiceFruit();
        juicerObj.stop();
        juicerObj.clean();
        juicerObj.drillTile();
        System.out.println("");
        IKeyboard keyboardObj = new KeyboardImpl();
        keyboardObj.type();
        keyboardObj.connect();
        keyboardObj.lightOn();
        keyboardObj.setAngle();
        System.out.println("");
        ILamp lampObj = new LampImpl();
        lampObj.turnOn();
        lampObj.dim();
        lampObj.changeColor();
        lampObj.wearGloves();
        System.out.println("");
        ILaptop laptopObj = new LaptopImpl();
        laptopObj.powerOn();
        laptopObj.powerOff();
        laptopObj.runProgram();
        laptopObj.insertBit();
        System.out.println("");
        ILight lightObj = new LightImpl();
        lightObj.switchOn();
        lightObj.switchOff();
        lightObj.dim();
        lightObj.drillMetal();
        System.out.println("");
        IMeasuringScale measuringScaleObj = new MeasuringScaleImpl();
        measuringScaleObj.weigh();
        measuringScaleObj.tare();
        measuringScaleObj.reset();
        measuringScaleObj.pushLightly();
        System.out.println("");
        IMicrowave microwaveObj = new MicrowaveImpl();
        microwaveObj.start();
        microwaveObj.stop();
        microwaveObj.setTimer();
        microwaveObj.useMask();
        System.out.println("");
        IMixer mixerObj = new MixerImpl();
        mixerObj.mix();
        mixerObj.grind();
        mixerObj.stop();
        mixerObj.wipeWall();
        System.out.println("");
        IMonitor monitorObj = new MonitorImpl();
        monitorObj.displayImage();
        monitorObj.adjustBrightness();
        monitorObj.turnOff();
        monitorObj.rechargeTool();
        System.out.println("");
        IMouse mouseObj = new MouseImpl();
        mouseObj.click();
        mouseObj.scroll();
        mouseObj.connect();
        mouseObj.readManual();
        System.out.println("");
        IOven ovenObj = new OvenImpl();
        ovenObj.preheat();
        ovenObj.bake();
        ovenObj.grill();
        ovenObj.testDrill();
        System.out.println("");
        IPhone phoneObj = new PhoneImpl();
        phoneObj.makeCall();
        phoneObj.receiveCall();
        phoneObj.charge();
        phoneObj.chooseBit();
        System.out.println("");
        IPowerBank powerBankObj = new PowerBankImpl();
        powerBankObj.chargeDevice();
        powerBankObj.recharge();
        powerBankObj.checkStatus();
        powerBankObj.calibrateTool();
        System.out.println("");
        IPrinter printerObj = new PrinterImpl();
        printerObj.print();
        printerObj.scan();
        printerObj.copy();
        printerObj.aimSpot();
        System.out.println("");
        IProjector projectorObj = new ProjectorImpl();
        projectorObj.projectImage();
        projectorObj.adjustFocus();
        projectorObj.shutDown();
        projectorObj.braceWall();
        System.out.println("");

        IRefrigerator refrigeratorObj = new RefrigeratorImpl();
        refrigeratorObj.cool();
        refrigeratorObj.freeze();
        refrigeratorObj.defrost();
        refrigeratorObj.controlSpeed();
        System.out.println("");

        IRobot robotObj = new RobotImpl();
        robotObj.walk();
        robotObj.speak();
        robotObj.grabObject();
        robotObj.gripTool();
        System.out.println("");

        IRouter routerObj = new RouterImpl();
        routerObj.connect();
        routerObj.disconnect();
        routerObj.reset();
        routerObj.startDrill();
        System.out.println("");
        IScanner scannerObj = new ScannerImpl();
        scannerObj.scanDocument();
        scannerObj.scanImage();
        scannerObj.preview();
        scannerObj.finishEdge();
        System.out.println("");
        ISecurityCamera securityCameraObj = new SecurityCameraImpl();
        securityCameraObj.record();
        securityCameraObj.streamLive();
        securityCameraObj.alertMotion();
        securityCameraObj.measureTwice();
        System.out.println("");
        ISmartBulb smartBulbObj = new SmartBulbImpl();
        smartBulbObj.changeColor();
        smartBulbObj.dimLight();
        smartBulbObj.turnOff();
        smartBulbObj.storeTool();
        System.out.println("");
        ISmartFridge smartFridgeObj = new SmartFridgeImpl();
        smartFridgeObj.trackItems();
        smartFridgeObj.cool();
        smartFridgeObj.notify1();
        smartFridgeObj.lubricateBit();
        System.out.println("");
        ISmartLock smartLockObj = new SmartLockImpl();
        smartLockObj.lock();
        smartLockObj.unlock();
        smartLockObj.setPIN();
        smartLockObj.inspectWork();
        System.out.println("");
        ISmartMirror smartMirrorObj = new SmartMirrorImpl();
        smartMirrorObj.displayWeather();
        smartMirrorObj.showTime();
        smartMirrorObj.adjustBrightness();
        smartMirrorObj.lightArea();
        System.out.println("");
        ISmartPlug smartPlugObj = new SmartPlugImpl();
        smartPlugObj.turnOn();
        smartPlugObj.turnOff();
        smartPlugObj.schedule();
        smartPlugObj.lockChuck();
        System.out.println("");
        ISmartWatch smartWatchObj = new SmartWatchImpl();
        smartWatchObj.trackSteps();
        smartWatchObj.monitorHeartRate();
        smartWatchObj.displayTime();
        smartWatchObj.cleanBit();
        System.out.println("");
        ISoundBar soundBarObj = new SoundBarImpl();
        soundBarObj.turnOn();
        soundBarObj.adjustVolume();
        soundBarObj.connectBluetooth();
        soundBarObj.adjustTorque();
        System.out.println("");
        ISpeaker speakerObj = new SpeakerImpl();
        speakerObj.playMusic();
        speakerObj.pause();
        speakerObj.increaseVolume();
        speakerObj.stabilizeTool();
        System.out.println("");
        ISpeakerSystem speakerSystemObj = new SpeakerSystemImpl();
        speakerSystemObj.turnOn();
        speakerSystemObj.adjustBass();
        speakerSystemObj.mute();
        speakerSystemObj.markLevel();
        System.out.println("");
        ISprinkler sprinklerObj = new SprinklerImpl();
        sprinklerObj.start();
        sprinklerObj.stop();
        sprinklerObj.schedule();
        sprinklerObj.holdFirm();
        System.out.println("");
        ISwitch switchObj = new SwitchImpl();
        switchObj.flipOn();
        switchObj.flipOff();
        switchObj.status();
        switchObj.alignBracket();
        System.out.println("");
        ITablet tabletObj = new TabletImpl();
        tabletObj.tap();
        tabletObj.swipe();
        tabletObj.installApp();
        tabletObj.testFit();
        System.out.println("");
        ITelevision televisionObj = new TelevisionImpl();
        televisionObj.powerOn();
        televisionObj.powerOff();
        televisionObj.changeChannel();
        televisionObj.reviewPlan();
        System.out.println("");
        IThermometer thermometerObj = new ThermometerImpl();
        thermometerObj.measureTemp();
        thermometerObj.reset();
        thermometerObj.calibrate();
        thermometerObj.cutThrough();
        System.out.println("");
        IThermostat thermostatObj = new ThermostatImpl();
        thermostatObj.setTemp();
        thermostatObj.increaseTemp();
        thermostatObj.decreaseTemp();
        thermostatObj.wearGoggles();
        System.out.println("");
        IToaster toasterObj = new ToasterImpl();
        toasterObj.insertBread();
        toasterObj.toast();
        toasterObj.eject();
        toasterObj.checkAlignment();
        System.out.println("");
        ITreadmill treadmillObj = new TreadmillImpl();
        treadmillObj.start();
        treadmillObj.stop();
        treadmillObj.adjustIncline();
        treadmillObj.clearDebris();
        System.out.println("");
        ITVRemote tVRemoteObj = new TVRemoteImpl();
        tVRemoteObj.changeChannel();
        tVRemoteObj.increaseVolume();
        tVRemoteObj.mute();
        tVRemoteObj.smoothHole();
        System.out.println("");
        IVacuumCleaner vacuumCleanerObj = new VacuumCleanerImpl();
        vacuumCleanerObj.start();
        vacuumCleanerObj.stop();
        vacuumCleanerObj.changeMode();
        vacuumCleanerObj.testHold();
        System.out.println("");
        IWashingMachine washingMachineObj = new WashingMachineImpl();
        washingMachineObj.wash();
        washingMachineObj.rinse();
        washingMachineObj.spin();
        washingMachineObj.resetBit();
        System.out.println("");
        IWatch watchObj = new WatchImpl();
        watchObj.showTime();
        watchObj.startTimer();
        watchObj.stopTimer();
        watchObj.turnOff();
        System.out.println("");
        IWaterPump waterPumpObj = new WaterPumpImpl();
        waterPumpObj.start();
        waterPumpObj.stop();
        waterPumpObj.setFlowRate();
        waterPumpObj.sealGap();
        System.out.println("");
        IWIFIExtender wIFIExtenderObj = new WIFIExtenderImpl();
        wIFIExtenderObj.boostSignal();
        wIFIExtenderObj.connectDevice();
        wIFIExtenderObj.restart();
        wIFIExtenderObj.labelSpot();
        System.out.println("");
        IWindowBlind windowBlindObj = new WindowBlindImpl();
        windowBlindObj.open();
        windowBlindObj.close();
        windowBlindObj.adjustTilt();
        windowBlindObj.handleTool();
        System.out.println("");
    }
}